// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> en = {
  "Discover": "Discover",
  "Find Inspiration, Explore Fascinating Destination With Us": "Find Inspiration, Explore Fascinating Destination With Us",
  "Plan Your Trip": "Plan Your Trip",
  "Select Destinations And Start Scheduling Details For Your Trip": "Select Destinations And Start Scheduling Details For Your Trip",
  "Start Your Journey": "Start Your Journey",
  "Enjoy! Relax And Chilling Memories": "Enjoy! Relax And Chilling Memories",
  "Share Your Trip": "Share Your Trip",
  "Share Your Experience In Your Trip And Connect with Travel Lovers Around The World": "Share Your Experience In Your Trip And Connect with Travel Lovers Around The World",
  "GET START": "GET START",
  "downTitleOnBoardingScreen": "I’m not the new one",
  "Welcome To Travel X": "Welcome To Travel X",
  "Sign Up": "sign Up",
  "Sign In": "Sign In",
  "Or": "Or",
  "Wishlist Activity": "Wishlist Activity",
  "Wishlist Hotel": "Wishlist Hotel",
  "Settings": "Settings",
  "Account Settings": "Account Settings",
  "Personal information": "Personal information",
  "Change password": "Change password",
  "More": "More",
  "About Us": "About Us",
  "Privacy policy": "Privacy policy",
  "Room Number": "Room Number",
  "Check In": "Check In",
  "Check Out": "Check Out",
  "Guest": "Guest",
  "Price": "Price",
  "Select Room": "Select Room",
  "Tickets": "Tickets",
  "Activity Tickets": "Activity Tickets",
  "Rooms Tickets": "Rooms Tickets",
  "Search": "Search",
  "Room History": "Room History",
  "Profile": "Profile",
  "Wishlist Hotels": "Wishlist Hotels",
  "Wishlist Activities": "Wishlist Activities",
  "Activities History'": "Activities History'",
  "Rooms History": "Rooms History",
  "Explore Destination": "Explore Destination",
  "Explore Nearby Places": "Explore Nearby Places",
  "Hi": "Hi",
  "Hotel": "Hotel",
  "About": "About",
  "Description": "Description",
  "Booking": "Booking",
  "Reviews": "Reviews",
  "km from current location": "km from current location",
  "select Days": "select Days",
  "Location": "Location",
  "Facilities": "Facilities",
  "Make Review": "Make Review",
  "Number of Days": "Number of Days",
  "Description Activity": "Description Activity",
  "Book Now": "Book Now",
  "Booked Activity": "Booked Activity",
  "Category": "Category",
  "How Many People": "How Many People",
  "Payment Method Available": "Payment Method Available",
  "Cash": "Cash",
  "Visa": "Visa",
  "Booked Now": "Booked Now",
  "Fill in Details": "Fill in Details",
  "Next": "Next",
  "Sign In To Travel": "Sign In To Travel",
  "Email": "Email",
  "password": "password"
};
static const Map<String,dynamic> ar = {
  "Discover": "أكتشف",
  "Find Inspiration, Explore Fascinating Destination With Us": "ابحث عن الإلهام واستكشف أماكن رائعة معن",
  "Plan Your Trip": "خطط لرحلتك",
  "Select Destinations And Start Scheduling Details For Your Trip": "حدد الوجهات وابدأ في جدولة التفاصيل لرحلتك",
  "Start Your Journey": "ابدأ رحلتك",
  "Enjoy! Relax And Chilling Memories": "أستمتع!بالهدوء واصنع ذكرياتك",
  "Share Your Trip": "شارك رحلتك",
  "GET START": "أبدا",
  "Share Your Experience In Your Trip And Connect with Travel Lovers Around The World": "شارك رحلتك وتواصل مع محبي السفر حول العالم",
  "downTitleOnBoardingScreen": "لست زائر جديد",
  "skip": "تخطي",
  "Welcome To Travel X": "مرحبا بك في ترافيل اكس",
  "Sign Up": "أنشاء حساب",
  "Sign In": "تسجيل دخول",
  "Or": "أو",
  "Wishlist Activity": "تفضيلات الانشطه",
  "Wishlist Hotel": "تفضيلات الفنادق",
  "Settings": "الاعدادات",
  "Account Settings": "أعدادات الحساب",
  "Personal information": "معلومات الحساب",
  "Change password": "تغير كلمة المرور",
  "More": "المزيد",
  "About Us": "عن الابليكشن",
  "Privacy policy": "الاتفاق",
  "Room Number": "رقم الغرفه",
  "Check In": "معاد الحضور",
  "Check Out": "معاد الانصراف",
  "Guest": "الاشخاص",
  "Price": "السعر",
  "Select Room": "حدد الغرفه",
  "Tickets": "االتذكره",
  "Activity Tickets": "تذاكر النشاط",
  "Rooms Tickets": "تذكره الغرفه",
  "Search": "البحث",
  "Room History": "الغرف السابقه",
  "Profile": "الملف الشخصي",
  "Wishlist Hotels": "الفنادق المفضله",
  "Wishlist Activities": "الانشطه المفضله",
  "Activities History": "الانشطه السابقه'",
  "Rooms History": "الغرف السابقه",
  "Explore Destination": "أستكشف المزيد من الاماكن",
  "Explore Nearby Places": "استكشف الاماكن القريبه لك",
  "Hi": "مرحبا ",
  "Hotel": "فندق",
  "About": "معلومات عن الفدق",
  "Description": "وصف عن الفندق",
  "Booking": "حجز الفندق",
  "Reviews": "التقيمات",
  "km from current location": "المسافه التقديريه هي ",
  "select Days": "تحديد الايام",
  "Location": "الموقع",
  "Facilities": "الخصائص",
  "Make Review": "عبر عن رايك",
  "Number of Days": "عدد الايام",
  "Description Activity": "وصف النشاط",
  "Book Now": "حجز الان",
  "Booked Activity": "حجز نشاط",
  "Category": "التصنيف",
  "How Many People ": "عدد الاشخاص",
  "Payment Method Available": "طرق الدفع المتاحه",
  "Cash": "دفع نقدي",
  "Visa": "دفع عن طريق البطاقه",
  "Booked Now": "حجز الان",
  "Fill in Details": "الفاتوره",
  "Next": "التالي",
  "Sign In To Travel": "تسجيل الدخول",
  "Email": "البريد الالكتروني",
  "password": "كلمه المرور"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": en, "ar": ar};
}
